# Generated by Django 5.2.3 on 2025-06-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantcombination',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
