# Generated by Django 5.2.3 on 2025-06-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariantcombination_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='review_count',
            field=models.IntegerField(default=100),
        ),
    ]
