# Generated by Django 5.2.3 on 2025-06-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_discount_alter_products_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantcombination',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariantcombination',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariantcombination',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AlterField(
            model_name='productvariantcombination',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
